with open("app/cases/page.tsx", encoding="utf-8") as f:
    content = f.read()

new_cases = """
    {
      id: 9,
      title: language === 'hi' ? "ए.के. गोपालन बनाम मद्रास राज्य" : "A.K. Gopalan v. State of Madras",
      citation: "AIR 1950 SC 27",
      year: 1950,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ H.J. Kania",
      category: "Fundamental Rights",
      categoryLabel: language === 'hi' ? "मौलिक अधिकार" : "Fundamental Rights",
      keywords: language === 'hi' ? ["अनुच्छेद 21", "निवारक निरोध", "व्यक्तिगत स्वतंत्रता"] : ["Article 21", "Preventive Detention", "Personal Liberty"],
      summary: language === 'hi' ? "सुप्रीम कोर्ट का पहला बड़ा संवैधानिक मामला। माना गया कि अनुच्छेद 21 के तहत कानून द्वारा स्थापित प्रक्रिया का अर्थ केवल विधायिका द्वारा बनाई गई प्रक्रिया है। बाद में मेनका गांधी मामले में इसे पलट दिया गया।" : "First major constitutional case of the Supreme Court. Held that procedure established by law under Article 21 means only the procedure enacted by the legislature. Later overruled in Maneka Gandhi case.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#0066ff",
    },
    {
      id: 10,
      title: language === 'hi' ? "गोलकनाथ बनाम पंजाब राज्य" : "Golaknath v. State of Punjab",
      citation: "AIR 1967 SC 1643",
      year: 1967,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ K. Subba Rao (11-Judge Bench)",
      category: "Constitutional",
      categoryLabel: language === 'hi' ? "संवैधानिक" : "Constitutional",
      keywords: language === 'hi' ? ["मौलिक अधिकार", "संवैधानिक संशोधन", "अनुच्छेद 368"] : ["Fundamental Rights", "Constitutional Amendment", "Article 368"],
      summary: language === 'hi' ? "माना गया कि संसद मौलिक अधिकारों में संशोधन नहीं कर सकती। यह निर्णय बाद में केशवानंद भारती मामले में पलट दिया गया, लेकिन मूल संरचना सिद्धांत की नींव रखी।" : "Held that Parliament cannot amend Fundamental Rights. This decision was later overruled in Kesavananda Bharati, but laid the foundation for the Basic Structure doctrine.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#7c3aed",
    },
    {
      id: 11,
      title: language === 'hi' ? "मिनर्वा मिल्स बनाम भारत संघ" : "Minerva Mills v. Union of India",
      citation: "AIR 1980 SC 1789",
      year: 1980,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ Y.V. Chandrachud",
      category: "Constitutional",
      categoryLabel: language === 'hi' ? "संवैधानिक" : "Constitutional",
      keywords: language === 'hi' ? ["मूल संरचना", "42वां संशोधन", "न्यायिक समीक्षा"] : ["Basic Structure", "42nd Amendment", "Judicial Review"],
      summary: language === 'hi' ? "42वें संशोधन की धाराओं को रद्द किया जो न्यायिक समीक्षा को सीमित करती थीं। माना गया कि मौलिक अधिकारों और निदेशक तत्वों के बीच सामंजस्य संविधान की मूल संरचना का हिस्सा है।" : "Struck down provisions of the 42nd Amendment that curtailed judicial review. Held that harmony between Fundamental Rights and Directive Principles is part of the basic structure.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#ff4d6d",
    },
    {
      id: 12,
      title: language === 'hi' ? "एम.सी. मेहता बनाम भारत संघ (ताज ट्रेपेज़ियम)" : "M.C. Mehta v. Union of India (Taj Trapezium)",
      citation: "(1997) 2 SCC 353",
      year: 1997,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. Kuldip Singh",
      category: "Environment",
      categoryLabel: language === 'hi' ? "पर्यावरण" : "Environment",
      keywords: language === 'hi' ? ["पर्यावरण संरक्षण", "ताज महल", "प्रदूषण", "अनुच्छेद 21"] : ["Environmental Protection", "Taj Mahal", "Pollution", "Article 21"],
      summary: language === 'hi' ? "ताज महल के आसपास प्रदूषण फैलाने वाले उद्योगों को बंद करने या स्थानांतरित करने का आदेश दिया। माना गया कि स्वच्छ पर्यावरण का अधिकार अनुच्छेद 21 के तहत जीवन के अधिकार का हिस्सा है।" : "Ordered closure or relocation of polluting industries around the Taj Mahal. Held that the right to a clean environment is part of the right to life under Article 21.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#4ade80",
    },
    {
      id: 13,
      title: language === 'hi' ? "एम.सी. मेहता बनाम भारत संघ (गंगा प्रदूषण)" : "M.C. Mehta v. Union of India (Ganga Pollution)",
      citation: "AIR 1988 SC 1037",
      year: 1988,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. E.S. Venkataramiah",
      category: "Environment",
      categoryLabel: language === 'hi' ? "पर्यावरण" : "Environment",
      keywords: language === 'hi' ? ["गंगा प्रदूषण", "पर्यावरण", "जनहित याचिका"] : ["Ganga Pollution", "Environment", "PIL"],
      summary: language === 'hi' ? "गंगा नदी में प्रदूषण फैलाने वाले टेनरियों और उद्योगों को बंद करने का आदेश दिया। पर्यावरण संरक्षण के लिए जनहित याचिका के उपयोग को स्थापित किया। प्रदूषक भुगतान सिद्धांत लागू किया।" : "Ordered closure of tanneries and industries polluting the Ganga river. Established the use of PIL for environmental protection. Applied the polluter pays principle.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#4ade80",
    },
    {
      id: 14,
      title: language === 'hi' ? "हुसैनारा खातून बनाम बिहार राज्य" : "Hussainara Khatoon v. State of Bihar",
      citation: "AIR 1979 SC 1360",
      year: 1979,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. P.N. Bhagwati",
      category: "Criminal Law",
      categoryLabel: language === 'hi' ? "आपराधिक कानून" : "Criminal Law",
      keywords: language === 'hi' ? ["त्वरित सुनवाई", "विचाराधीन कैदी", "अनुच्छेद 21", "जमानत"] : ["Speedy Trial", "Undertrial Prisoners", "Article 21", "Bail"],
      summary: language === 'hi' ? "माना गया कि त्वरित सुनवाई अनुच्छेद 21 के तहत एक मौलिक अधिकार है। बिहार की जेलों में वर्षों से बंद विचाराधीन कैदियों को रिहा करने का आदेश दिया।" : "Held that speedy trial is a fundamental right under Article 21. Ordered release of undertrial prisoners languishing in Bihar jails for years.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#0066ff",
    },
    {
      id: 15,
      title: language === 'hi' ? "डी.के. बसु बनाम पश्चिम बंगाल राज्य" : "D.K. Basu v. State of West Bengal",
      citation: "(1997) 1 SCC 416",
      year: 1997,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. A.S. Anand",
      category: "Criminal Law",
      categoryLabel: language === 'hi' ? "आपराधिक कानून" : "Criminal Law",
      keywords: language === 'hi' ? ["पुलिस हिरासत", "हिरासत में मौत", "गिरफ्तारी दिशानिर्देश", "अनुच्छेद 21"] : ["Police Custody", "Custodial Death", "Arrest Guidelines", "Article 21"],
      summary: language === 'hi' ? "पुलिस गिरफ्तारी और हिरासत के लिए विस्तृत दिशानिर्देश जारी किए। गिरफ्तार व्यक्ति को गिरफ्तारी का कारण बताना, परिवार को सूचित करना, चिकित्सा जांच अनिवार्य। हिरासत में यातना और मौत के लिए राज्य उत्तरदायी।" : "Issued detailed guidelines for police arrest and detention. Mandatory to inform arrested person of grounds, notify family, conduct medical examination. State liable for custodial torture and death.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#ff4d6d",
    },
    {
      id: 16,
      title: language === 'hi' ? "बंधुआ मुक्ति मोर्चा बनाम भारत संघ" : "Bandhua Mukti Morcha v. Union of India",
      citation: "AIR 1984 SC 802",
      year: 1984,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. P.N. Bhagwati",
      category: "Socio-Economic Rights",
      categoryLabel: language === 'hi' ? "सामाजिक-आर्थिक अधिकार" : "Socio-Economic Rights",
      keywords: language === 'hi' ? ["बंधुआ मजदूरी", "अनुच्छेद 21", "अनुच्छेद 23", "मानव गरिमा"] : ["Bonded Labour", "Article 21", "Article 23", "Human Dignity"],
      summary: language === 'hi' ? "बंधुआ मजदूरी को अनुच्छेद 21 और 23 का उल्लंघन माना। सरकार को बंधुआ मजदूरों की पहचान, मुक्ति और पुनर्वास का निर्देश दिया।" : "Held bonded labour to be a violation of Articles 21 and 23. Directed the government to identify, release, and rehabilitate bonded labourers.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#f59e0b",
    },
    {
      id: 17,
      title: language === 'hi' ? "शायरा बानो बनाम भारत संघ (तीन तलाक)" : "Shayara Bano v. Union of India (Triple Talaq)",
      citation: "(2017) 9 SCC 1",
      year: 2017,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: language === 'hi' ? "5-न्यायाधीशों की संविधान पीठ" : "5-Judge Constitution Bench",
      category: "Women's Rights",
      categoryLabel: language === 'hi' ? "महिलाओं के अधिकार" : "Women's Rights",
      keywords: language === 'hi' ? ["तीन तलाक", "मुस्लिम महिला", "अनुच्छेद 14", "मनमाना"] : ["Triple Talaq", "Muslim Women", "Article 14", "Arbitrary"],
      summary: language === 'hi' ? "तत्काल तीन तलाक को 3:2 बहुमत से असंवैधानिक घोषित किया। माना गया कि यह प्रथा मनमाना और अनुच्छेद 14 का उल्लंघन है। इसके बाद मुस्लिम महिला संरक्षण अधिनियम 2019 पारित किया गया।" : "Declared instant triple talaq unconstitutional by 3:2 majority. Held the practice to be arbitrary and violative of Article 14. Led to the Muslim Women Protection Act 2019.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#f472b6",
    },
    {
      id: 18,
      title: language === 'hi' ? "श्रेया सिंघल बनाम भारत संघ" : "Shreya Singhal v. Union of India",
      citation: "(2015) 5 SCC 1",
      year: 2015,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. J. Chelameswar",
      category: "Media & Speech",
      categoryLabel: language === 'hi' ? "मीडिया और भाषण" : "Media & Speech",
      keywords: language === 'hi' ? ["धारा 66A", "IT अधिनियम", "इंटरनेट स्वतंत्रता", "अभिव्यक्ति"] : ["Section 66A", "IT Act", "Internet Freedom", "Expression"],
      summary: language === 'hi' ? "IT अधिनियम की धारा 66A को असंवैधानिक घोषित किया जो ऑनलाइन आपत्तिजनक सामग्री पोस्ट करने को अपराध बनाती थी। माना गया कि यह अनुच्छेद 19(1)(a) के तहत अभिव्यक्ति की स्वतंत्रता का उल्लंघन है।" : "Struck down Section 66A of the IT Act which criminalized posting offensive content online. Held it to be a violation of freedom of expression under Article 19(1)(a).",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#4f46e5",
    },
    {
      id: 19,
      title: language === 'hi' ? "इंडियन यंग लॉयर्स एसोसिएशन बनाम केरल राज्य (सबरीमाला)" : "Indian Young Lawyers Association v. State of Kerala (Sabarimala)",
      citation: "(2019) 11 SCC 1",
      year: 2018,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ Dipak Misra (5-Judge Bench)",
      category: "Civil Rights",
      categoryLabel: language === 'hi' ? "नागरिक अधिकार" : "Civil Rights",
      keywords: language === 'hi' ? ["सबरीमाला", "महिला प्रवेश", "अनुच्छेद 25", "धार्मिक स्वतंत्रता"] : ["Sabarimala", "Women Entry", "Article 25", "Religious Freedom"],
      summary: language === 'hi' ? "4:1 बहुमत से माना गया कि सबरीमाला मंदिर में 10-50 वर्ष की महिलाओं के प्रवेश पर प्रतिबंध असंवैधानिक है। भक्ति और पूजा का अधिकार लिंग के आधार पर प्रतिबंधित नहीं किया जा सकता।" : "Held by 4:1 majority that the ban on entry of women aged 10-50 in Sabarimala temple is unconstitutional. The right to devotion and worship cannot be restricted on the basis of gender.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#f59e0b",
    },
    {
      id: 20,
      title: language === 'hi' ? "सुप्रीम कोर्ट एडवोकेट्स-ऑन-रिकॉर्ड बनाम भारत संघ (NJAC)" : "Supreme Court Advocates-on-Record v. Union of India (NJAC)",
      citation: "(2016) 5 SCC 1",
      year: 2015,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: language === 'hi' ? "5-न्यायाधीशों की संविधान पीठ" : "5-Judge Constitution Bench",
      category: "Constitutional",
      categoryLabel: language === 'hi' ? "संवैधानिक" : "Constitutional",
      keywords: language === 'hi' ? ["न्यायिक नियुक्ति", "NJAC", "कॉलेजियम", "न्यायपालिका की स्वतंत्रता"] : ["Judicial Appointment", "NJAC", "Collegium", "Judicial Independence"],
      summary: language === 'hi' ? "99वें संवैधानिक संशोधन और NJAC अधिनियम को रद्द किया। माना गया कि न्यायपालिका की स्वतंत्रता संविधान की मूल संरचना का हिस्सा है। कॉलेजियम प्रणाली को बहाल किया।" : "Struck down the 99th Constitutional Amendment and the NJAC Act. Held that independence of judiciary is part of the basic structure. Restored the collegium system.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#00d4ff",
    },
    {
      id: 21,
      title: language === 'hi' ? "रोमेश थापर बनाम मद्रास राज्य" : "Romesh Thappar v. State of Madras",
      citation: "AIR 1950 SC 124",
      year: 1950,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ H.J. Kania",
      category: "Media & Speech",
      categoryLabel: language === 'hi' ? "मीडिया और भाषण" : "Media & Speech",
      keywords: language === 'hi' ? ["प्रेस की स्वतंत्रता", "अनुच्छेद 19", "अभिव्यक्ति की स्वतंत्रता"] : ["Press Freedom", "Article 19", "Freedom of Expression"],
      summary: language === 'hi' ? "प्रेस की स्वतंत्रता को अनुच्छेद 19(1)(a) के तहत अभिव्यक्ति की स्वतंत्रता का हिस्सा माना। माना गया कि सार्वजनिक व्यवस्था के आधार पर प्रतिबंध केवल तभी वैध है जब यह राज्य की सुरक्षा को खतरे से जुड़ा हो।" : "Held that freedom of press is part of freedom of expression under Article 19(1)(a). Restriction on grounds of public order is valid only when connected to a threat to the security of the State.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#4f46e5",
    },
    {
      id: 22,
      title: language === 'hi' ? "अरुणा शानबाग बनाम भारत संघ" : "Aruna Shanbaug v. Union of India",
      citation: "(2011) 4 SCC 454",
      year: 2011,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. Markandey Katju",
      category: "Fundamental Rights",
      categoryLabel: language === 'hi' ? "मौलिक अधिकार" : "Fundamental Rights",
      keywords: language === 'hi' ? ["इच्छामृत्यु", "जीवन का अधिकार", "अनुच्छेद 21", "गरिमा"] : ["Euthanasia", "Right to Life", "Article 21", "Dignity"],
      summary: language === 'hi' ? "निष्क्रिय इच्छामृत्यु को कड़े दिशानिर्देशों के साथ अनुमति दी। माना गया कि गरिमा के साथ मरने का अधिकार अनुच्छेद 21 के तहत जीवन के अधिकार का हिस्सा है। सक्रिय इच्छामृत्यु को अवैध माना।" : "Permitted passive euthanasia with strict guidelines. Held that the right to die with dignity is part of the right to life under Article 21. Active euthanasia held to be illegal.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#7c3aed",
    },
    {
      id: 23,
      title: language === 'hi' ? "पीपुल्स यूनियन फॉर सिविल लिबर्टीज बनाम भारत संघ (PUCL)" : "PUCL v. Union of India (Right to Food)",
      citation: "(2003) 2 SCC 1",
      year: 2001,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. Kirpal",
      category: "Socio-Economic Rights",
      categoryLabel: language === 'hi' ? "सामाजिक-आर्थिक अधिकार" : "Socio-Economic Rights",
      keywords: language === 'hi' ? ["भोजन का अधिकार", "अनुच्छेद 21", "मध्याह्न भोजन", "भूख"] : ["Right to Food", "Article 21", "Mid-Day Meal", "Hunger"],
      summary: language === 'hi' ? "भोजन के अधिकार को अनुच्छेद 21 के तहत जीवन के अधिकार का हिस्सा माना। सभी सरकारी स्कूलों में मध्याह्न भोजन योजना लागू करने का आदेश दिया। खाद्य सुरक्षा कानून की नींव रखी।" : "Held the right to food as part of the right to life under Article 21. Ordered implementation of mid-day meal scheme in all government schools. Laid the foundation for food security legislation.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#4ade80",
    },
    {
      id: 24,
      title: language === 'hi' ? "नाज फाउंडेशन बनाम दिल्ली सरकार" : "Naz Foundation v. Government of NCT of Delhi",
      citation: "160 (2009) DLT 277",
      year: 2009,
      court: language === 'hi' ? "दिल्ली उच्च न्यायालय" : "Delhi High Court",
      judge: "CJ A.P. Shah",
      category: "Civil Rights",
      categoryLabel: language === 'hi' ? "नागरिक अधिकार" : "Civil Rights",
      keywords: language === 'hi' ? ["धारा 377", "LGBTQ+", "समलैंगिकता", "अनुच्छेद 21"] : ["Section 377", "LGBTQ+", "Homosexuality", "Article 21"],
      summary: language === 'hi' ? "दिल्ली उच्च न्यायालय ने IPC की धारा 377 को वयस्कों के बीच सहमति से समलैंगिक संबंधों के लिए असंवैधानिक माना। यह निर्णय बाद में सुरेश कुमार कौशल मामले में पलट दिया गया, लेकिन नवतेज जौहर मामले में फिर से बहाल किया गया।" : "Delhi High Court held Section 377 IPC unconstitutional for consensual same-sex relations between adults. This was later overruled in Suresh Kumar Koushal but restored in Navtej Johar.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#f472b6",
    },
    {
      id: 25,
      title: language === 'hi' ? "राजस्थान राज्य बनाम विद्यावती" : "State of Rajasthan v. Vidyawati",
      citation: "AIR 1962 SC 933",
      year: 1962,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "J. S.K. Das",
      category: "Fundamental Rights",
      categoryLabel: language === 'hi' ? "मौलिक अधिकार" : "Fundamental Rights",
      keywords: language === 'hi' ? ["राज्य दायित्व", "सरकारी वाहन", "टोर्ट", "मुआवजा"] : ["State Liability", "Government Vehicle", "Tort", "Compensation"],
      summary: language === 'hi' ? "माना गया कि राज्य अपने कर्मचारियों के लापरवाही भरे कार्यों के लिए उत्तरदायी है। सरकारी वाहन से दुर्घटना में मृत्यु के लिए राज्य को मुआवजा देना होगा। राज्य की संप्रभु प्रतिरक्षा को सीमित किया।" : "Held that the State is liable for negligent acts of its employees. State must pay compensation for death caused by a government vehicle accident. Limited the doctrine of sovereign immunity.",
      significance: language === 'hi' ? "ऐतिहासिक" : "Landmark",
      color: "#00b4d8",
    },
    {
      id: 26,
      title: language === 'hi' ? "मोहम्मद अहमद खान बनाम शाह बानो बेगम" : "Mohd. Ahmed Khan v. Shah Bano Begum",
      citation: "AIR 1985 SC 945",
      year: 1985,
      court: language === 'hi' ? "सुप्रीम कोर्ट" : "Supreme Court",
      judge: "CJ Y.V. Chandrachud",
      category: "Women's Rights",
      categoryLabel: language === 'hi' ? "महिलाओं के अधिकार" : "Women's Rights",
"""
# Insert new cases before the closing ], [language]);
insertion_point = '      significance: language === \'hi\' ? "ऐतिहासिक" : "Landmark",\n      color: "#4f46e5",\n    },\n  ], [language]);'

replacement = '      significance: language === \'hi\' ? "ऐतिहासिक" : "Landmark",\n      color: "#4f46e5",\n    },' + new_cases + '\n  ], [language]);'

new_content = content.replace(insertion_point, replacement)

with open("app/cases/page.tsx", "w", encoding="utf-8") as f:f.write(new_content)

print("Done! Cases added.")
